In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
#load data
dataset = load_iris()

In [23]:
class svmClassifier(object):
    def __init__(self, X, Y, numIterations=100, reg=1, delta=1):
        """
        Input
        X: training data
        Y: training labels
        """
        self.numIterations = numIterations
        self.reg = reg
        # bias trick, add row of ones to input
        self.Xdata = np.concatenate([X, np.ones([X.shape[0], 1])], axis=1)
        self.Ylabels = Y
        print("shape", self.Xdata.shape)
        #self.W = np.zeros([self.Xdata.shape[1], np.max(Y) + 1])
        self.W = np.random.randn(self.Xdata.shape[1], np.max(Y) + 1) * 0.0001
        print("w", self.W.shape)
        self.delta = delta
    def loss(self):
        numTrain = self.Xdata.shape[0]
        numClasses = np.max(Y) + 1
        dotXW = np.dot(self.Xdata, self.W)
        dW = np.zeros(self.W.shape)
        loss = 0.0
        deltas = self.delta*np.ones(dotXW.shape)
        scorePos = dotXW[np.arange(numTrain), Y]
        scorePosMatrix = np.repeat(np.array([scorePos,]).transpose(), numClasses, axis=1)
        
        # loss computation
        print(dotXW.shape)
        print(scorePosMatrix.shape)
        argHinge = dotXW - scorePosMatrix + deltas
        argHinge[np.arange(numTrain), Y] = 0
        idx = argHinge > 0
        evalHinge = argHinge * idx
        loss = np.sum(evalHinge)
        loss /= numTrain
        loss += self.reg * np.sum(self.W*self.W)
        
        # gradients computation
        Xmat = np.zeros(dotXW.shape)
        Xmat[idx] = 1
        numIncorrect = -1 * np.sum(Xmat, axis=1)
        Xmat[np.arange(numTrain), Y] = numIncorrect

        dW = np.dot(self.Xdata.T, Xmat)
        dW /= numTrain
        dW += 2*self.reg*self.W
        return loss, dW
    def train(self):
        """
        Method for training the svm. It updates the W parameters
        """
        pass
    def getW(self):
        """
        Testing method to get W
        output
        W: parameters from classifier
        """
        return self.W

In [24]:
X = dataset.data
Y = dataset.target
print(X[:4], Y[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]] [0 0 0 0]


In [25]:
svm  = svmClassifier(X, Y)

shape (150, 5)
w (5, 3)


In [ ]:
wp = svm.getW()
print(wp.shape, wp[:,0])

In [ ]:
a = np.array([[1,1,2],[1,2,3]])
b = np.array([[1, 2],[2, 2],[3,1]])
print(a.shape, b.shape)
print(np.dot(a, b))

In [ ]:
print(a)
print("transpose")
print(a.T)
print(np.arange(2))
z = a[np.arange(2),[0,2]]
print("smell", z, z.transpose())
c = np.repeat(np.array([z,]).transpose(), 3, axis=1)
print(c, np.sum(c, axis=0))
print(a - c)

In [ ]:
idx = a > 1
print(idx)
print(a*idx)
print(np.sum(a*idx))

In [26]:
# check loss and gradient
print(svm.loss())

(150, 3)
(150, 3)
(2.0001550046715435, array([[ 8.37097074e-01, -9.24055437e-02, -7.44882025e-01],
       [-3.70565389e-01,  2.87387396e-01,  8.34623696e-02],
       [ 2.29611735e+00, -5.02144267e-01, -1.79410029e+00],
       [ 9.53269345e-01, -1.26662134e-01, -8.26572930e-01],
       [-2.66034116e-04,  9.93857515e-05, -2.61524232e-04]]))
