In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:
#load data
dataset = load_iris()

In [4]:
class svmClassifier(object):
    def __init__(self, X, Y, numIterations=100, reg=1, delta=1):
        """
        Input
        X: training data
        Y: training labels
        """
        self.numIterations = numIterations
        self.reg = reg
        # bias trick, add row of ones to input
        self.Xdata = np.concatenate([X, np.ones([X.shape[0], 1])], axis=1)
        self.Ylabels = Y
        self.W = np.zeros([self.Xdata.shape[1], np.max(Y) + 1])
    def loss(self):
        numTrain = self.Xdata.shape[0]
        numClasses = np.max(Y)
        dotXW = np.dot(self.Xdata, self.W)
        dW = np.zeros(self.W.shape)
        loss = 0.0
        deltas = delta*np.ones(dotXW.shape)
        scorePos = dotXW[np.arange(numTrain), Y]
        scorePosMatrix = np.repeat(np.array([scorePos,]).transpose(), numClasses, axis=1)
        
        # loss computation
        argHinge = dotXW - scorePosMatrix + deltas
        argHinge[np.arange(numTrain), Y] = 0
        idx = argHinge > 0
        hingeEval = argHinge * idx
        loss = np.sum(hingeEval)
        loss /= numTrain
        loss += self.reg * np.sum(self.W*self.W)
        
        # gradients computation
        argHinge = dotXW - scorePosMatrix + deltas
        argHinge[np.arange(numTrain), Y] = 0
        idx = argHinge > 0
        evalHinge = argHinge * idx
        dW = self.Xdata 
        dW += 2*self.reg*self.W
        return loss, dW
    def train(self):
        """
        Method for training the svm. It updates the W parameters
        """
        pass
    def getW(self):
        """
        Testing method to get W
        output
        W: parameters from classifier
        """
        return self.W

In [9]:
X = dataset.data
Y = dataset.target
print(X.shape[0], Y[:4])

150 [0 0 0 0]


In [6]:
svm  = svmClassifier(X, Y)

In [7]:
wp = svm.getW()
print(wp.shape, wp[:,0])

(5, 3) [0. 0. 0. 0. 0.]


In [8]:
a = np.array([[1,1,2],[1,2,3]])
b = np.array([[1, 2],[2, 2],[3,1]])
print(a.shape, b.shape)

(2, 3) (3, 2)


In [34]:
print(a)
print(np.arange(2))
z = a[np.arange(2),[0,2]]
print("smell", z, z.transpose())
c = np.repeat(np.array([z,]).transpose(), 3, axis=1)
print(c, np.sum(c, axis=0))
print(a - c)

[[1 1 2]
 [1 2 3]]
[0 1]
smell [1 3] [1 3]
[[1 1 1]
 [3 3 3]] [4 4 4]
[[ 0  0  1]
 [-2 -1  0]]


In [ ]:
idx = a > 1
print(idx)
print(a*idx)
print(np.sum(a*idx))

In [ ]:
# check loss and gradient
